apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-base-values
  namespace: helm-flux-lab
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    replicaCount: 2
    service:
      type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-environment-values
  namespace: helm-flux-lab
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    replicaCount: 3
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: interview
  namespace: helm-flux-lab
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: my-first-chart
  valuesFrom:
    - kind: ConfigMap
      name: interview-base-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: interview-environment-values
      valuesKey: values.yaml
  values:
    replicaCount: 4
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  test:
    enable: true
  driftDetection:
    mode: enabled
